
      function agenda(opcion)
      {
        if(opcion == "home")
        {
          document.getElementById("home").style.display = 'block';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-home').addClass('pestana');         
          $('#a-menu1').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');

        }
        if(opcion == "menu1")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'block';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          $('#a-menu1').addClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          document.getElementById("canal11").style.display = 'block';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#menu11').addClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');



        }
        if(opcion == "menu2")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'block';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          $('#a_menu2').addClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a-menu1').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana'); 
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'block';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').addClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');         
        }
        if(opcion == "menu3")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'block';
          document.getElementById("menu4").style.display = 'none';
          $('#a_menu3').addClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a-menu1').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'block';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').addClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
        }
        if(opcion == "menu4")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'block';
          $('#a_menu4').addClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a-menu1').removeClass('pestana');
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'block';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').addClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
        }


        if(opcion == "canal11")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'block';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'block';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').addClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').addClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
          
        }
        if(opcion == "canal21")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'block';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'block';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').addClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').addClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
          
        }
        if(opcion == "canal31")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'block';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'block';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').addClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').addClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
          
        }
        if(opcion == "canal41")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'block';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'block';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').addClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').addClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
          
        }


        if(opcion == "canal12")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'block';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'block';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').addClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').addClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
          
        }
        if(opcion == "canal22")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'block';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'block';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').addClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').addClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
          
        }
        if(opcion == "canal32")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'block';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'block';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').addClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').addClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
          
        }
        if(opcion == "canal42")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'block';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'block';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').addClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').addClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
        }


        if(opcion == "canal13")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'block';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'block';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').addClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').addClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
          
        }
        if(opcion == "canal23")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'block';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'block';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').addClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').addClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
        }
        if(opcion == "canal33")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'block';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'block';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').addClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').addClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
        }
        if(opcion == "canal43")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'block';
          document.getElementById("menu4").style.display = 'none';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'block';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').addClass('pestana');
          $('#a_menu4').removeClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').addClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
        }


        if(opcion == "canal14")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'block';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'block';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('block');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').addClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
        }
        if(opcion == "canal24")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'block';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'block';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('block');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').addClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').removeClass('pestana');
        }
        if(opcion == "canal34")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'block';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'block';
          document.getElementById("canal44").style.display = 'none';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').removeClass('block');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').addClass('pestana');
          $('#menu44').removeClass('pestana');
        }
        if(opcion == "canal44")
        {
          document.getElementById("home").style.display = 'none';
          document.getElementById("menu1").style.display = 'none';
          document.getElementById("menu2").style.display = 'none';
          document.getElementById("menu3").style.display = 'none';
          document.getElementById("menu4").style.display = 'block';
          document.getElementById("canal11").style.display = 'none';
          document.getElementById("canal21").style.display = 'none';
          document.getElementById("canal31").style.display = 'none';
          document.getElementById("canal41").style.display = 'none';
          document.getElementById("canal12").style.display = 'none';
          document.getElementById("canal22").style.display = 'none';
          document.getElementById("canal32").style.display = 'none';
          document.getElementById("canal42").style.display = 'none';
          document.getElementById("canal13").style.display = 'none';
          document.getElementById("canal23").style.display = 'none';
          document.getElementById("canal33").style.display = 'none';
          document.getElementById("canal43").style.display = 'none';
          document.getElementById("canal14").style.display = 'none';
          document.getElementById("canal24").style.display = 'none';
          document.getElementById("canal34").style.display = 'none';
          document.getElementById("canal44").style.display = 'block';
          $('#a-menu1').removeClass('pestana');
          $('#a-home').removeClass('pestana');
          $('#a_menu2').removeClass('pestana');
          $('#a_menu3').removeClass('pestana');
          $('#a_menu4').addClass('pestana');
          $('#menu11').removeClass('pestana');          
          $('#menu12').removeClass('pestana');
          $('#menu13').removeClass('pestana');
          $('#menu14').removeClass('pestana');
          $('#menu21').removeClass('pestana');          
          $('#menu22').removeClass('pestana');
          $('#menu23').removeClass('pestana');
          $('#menu24').removeClass('pestana');
          $('#menu31').removeClass('pestana');          
          $('#menu32').removeClass('pestana');
          $('#menu33').removeClass('pestana');
          $('#menu34').removeClass('pestana');
          $('#menu41').removeClass('pestana');          
          $('#menu42').removeClass('pestana');
          $('#menu43').removeClass('pestana');
          $('#menu44').addClass('pestana');
        }


      }
